# week08/k8s/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-w10e1
type: Opaque # Indicates arbitrary user-defined data
data:
  # PostgreSQL Credentials (for both Product DB and Order DB)
  POSTGRES_USER: "cG9zdGdyZXM=" # Base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # Base64 for 'postgres'

  # Azure Storage Account Credentials for Product Service image uploads
  # REPLACE WITH YOUR ACTUAL BASE64 ENCODED VALUES from your Azure Storage Account
  # Example: echo -n 'myblobstorageaccount' | base64
  AZURE_STORAGE_ACCOUNT_NAME: "d2VlazEw" 
  # Example: echo -n 'your_storage_account_key_string' | base64
  AZURE_STORAGE_ACCOUNT_KEY: "eWxMNjZUKzFZbHBVUTJMMVRKWGc5clUrWis4NGdnSXpsQ2Z1R0xPZ0hNcUhmNjN6TVh2VUZQOTJ2VU1xTFphak9aS2FvbW44c21nUitBU3RTVXp3SXc9PQ=="
